### ISSUE TITLE
Arduino pin RX TX to MDB

### ISSUE THREAD

**Issue by bangjii** [LanguidSmartass/mdb-arduino-cashless#20]
I'm so sorry for my newbie experience in C++ AVR syntax, i want to ask which pin do you use to connect from arduino to MDB RX TX vending machine? Is it pin 0 and 1 (serial that using for programming)?
Ps i'm using Arduino MEGA2560.

**Comment by LanguidSmartass** [comment]
Please find and read the MDB interface description. You do not connect MCU
pins directly to MDB bus, you must use an optocoupler for each transmission
line.

There are also articles on the net on this subject which you can easily
find.
