### ISSUE TITLE
Vmc_commands

### ISSUE THREAD

**Issue by amsfec32** [LanguidSmartass/mdb-arduino-cashless#21]
Hello awesome code written for cashless device.
I have some problems in my case. My device gets reader enable command and according to program device goes to enabled state so vmc should not issue reader enable command until reader gets disabled. But my device getting reader enable multiple times. Second is, when reader issues a beginsession command and vmc should ack, nack, ret in the response of beginsession. But in my case my device is getting 0x12 byte which is poll. And sometimes session begun and  sometimes session does not begin. Do we need to set poll status to beginsession until device does not receive ack. Same with vendapproved and endsession command. Pls help
Thankyou

**Comment by mkrasselt1** [comment]
Hello :)
Some VMC doe reissue messages to make sure they are transmitted correctly - or if they are not aknowledged correclty.
So just ignore them if they are resend, or test if you dont aknowledge them correctly.
Do you get reset by the vmc from time to time ?

**Comment by amsfec32** [comment]
Thanks for you response.
When i issue beginsession command with available user funds, then sometimes vmc begins the session and show user credit on lcd but some times it ignores beginsession command so as i stydy in nama mdb spec4.2 that vmc does ack the sessionbegin command so i want to use that ack, nak, ret send by vmc to confirm that sessionbegin and if nak is received by reader then sessionbegin should be issue again.

**Comment by mkrasselt1** [comment]
i am not shure if i do understand correctly but yes, if vmc does not ack your session begin, you should do it again :)
we implemented as such, that the cashless device answers every poll with session begin, as long as the vmc did not change to session idle yet
